# Generated by Django 5.1.3 on 2025-03-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('hostel_type', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=10)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('single_beds', models.PositiveIntegerField()),
                ('shared_2_beds', models.PositiveIntegerField()),
                ('shared_3_beds', models.PositiveIntegerField()),
                ('price_single_bed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_shared_2_beds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_shared_3_beds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=15)),
                ('rules', models.TextField()),
                ('license_number', models.CharField(max_length=50)),
                ('amenities', models.TextField()),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostel_images/')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.hostelproperty')),
            ],
        ),
    ]
