# Generated by Django 5.1.3 on 2025-03-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hostelproperty_alter_contactus_options_hostelimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
