# Generated by Django 5.1.3 on 2025-03-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_hostel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelproperty',
            old_name='license_number',
            new_name='pan_number',
        ),
    ]
