# Generated by Django 5.1.3 on 2025-01-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hostel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
