# Generated by Django 5.1.3 on 2025-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='hostel_images/')),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('single_room_price', models.PositiveIntegerField(default=0)),
                ('two_sharing_price', models.PositiveIntegerField(default=0)),
                ('three_sharing_price', models.PositiveIntegerField(default=0)),
                ('single_room_available', models.PositiveIntegerField(default=0)),
                ('two_sharing_available', models.PositiveIntegerField(default=0)),
                ('three_sharing_available', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
