# Generated by Django 5.1.3 on 2025-03-17 08:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hostelproperty_latitude_hostelproperty_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelproperty',
            name='registration_certificate',
        ),
        migrations.CreateModel(
            name='RegisterCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='app.hostelproperty')),
            ],
        ),
    ]
