# Generated by Django 5.1.3 on 2025-03-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_hostelproperty_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelproperty',
            options={'verbose_name_plural': 'Hostel Details'},
        ),
    ]
