# Generated by Django 5.1.3 on 2025-03-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_hostelproperty_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
