# Generated by Django 5.1.3 on 2025-01-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
