# Generated by Django 5.1.3 on 2025-02-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, help_text="Enter the Font Awesome class for the icon, e.g., 'fa-wifi'", null=True, upload_to='facility_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='hostel_images/')),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('single_room_price', models.PositiveIntegerField(default=0)),
                ('two_sharing_price', models.PositiveIntegerField(default=0)),
                ('three_sharing_price', models.PositiveIntegerField(default=0)),
                ('single_room_available', models.PositiveIntegerField(default=0)),
                ('two_sharing_available', models.PositiveIntegerField(default=0)),
                ('three_sharing_available', models.PositiveIntegerField(default=0)),
                ('facilities', models.ManyToManyField(blank=True, to='app.facility')),
            ],
        ),
    ]
