# Generated by Django 5.1.3 on 2025-02-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_facility_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='facilities',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
