# Generated by Django 5.1.3 on 2025-02-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_hostel_facilities_delete_facility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True, help_text='Enter rules separated by a newline.')),
                ('single_room_price', models.PositiveIntegerField(default=0)),
                ('two_sharing_price', models.PositiveIntegerField(default=0)),
                ('three_sharing_price', models.PositiveIntegerField(default=0)),
                ('single_room_available', models.PositiveIntegerField(default=0)),
                ('two_sharing_available', models.PositiveIntegerField(default=0)),
                ('three_sharing_available', models.PositiveIntegerField(default=0)),
                ('facilities', models.TextField(blank=True)),
            ],
        ),
    ]
