# Generated by Django 5.1.3 on 2025-02-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
